      SUBROUTINE  F3D0(ALPHA,RX,RY,RZ,DEPTH,FP,FX,
     *               FY,FZ,UX,UY,UZ,UZX,UZY)
      IMPLICIT NONE
      DOUBLE PRECISION ALPHA,RX,RY,RZ,DEPTH,SZ,FP,
     *                 FX,FY,FZ,UX,UY,UZ,UZX,UZY

Cf2py intent(in) alpha,sx,sy,sz,depth,fp,fx,fy,fz
Cf2py intent(out) ux,uy,uz,uzx,uzy

      DOUBLE PRECISION U1_1, U2_1, U3_1, U1_2, U2_2,
     *                 U3_2, U1_3, U2_3, U3_3
      DOUBLE PRECISION U1_3_px1, U1_3_px2
      DOUBLE PRECISION U2_3_px1, U2_3_px2
      DOUBLE PRECISION U3_3_px1, U3_3_px2

      SZ = -DEPTH
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      ! code generated by sympy!
      ! here FP = F/(8*pi*mu)
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      U1_1 = 2*ALPHA*FP*RZ*SZ*(-3*RX**2/(RX**2 + RY**2 + (-RZ - SZ)**2)
     @ **(5.0d0/2.0d0) + (RX**2 + RY**2 + (-RZ - SZ)**2)**(-3.0d0/2.0d0
     @ )) - FP*(ALPHA*RX**2/(RX**2 + RY**2 + (-RZ - SZ)**2)**(3.0d0/
     @ 2.0d0) + (2 - ALPHA)/sqrt(RX**2 + RY**2 + (-RZ - SZ)**2)) + FP*(
     @ ALPHA*RX**2/(RX**2 + RY**2 + (RZ - SZ)**2)**(3.0d0/2.0d0) + (2 -
     @ ALPHA)/sqrt(RX**2 + RY**2 + (RZ - SZ)**2)) + 2*FP*(RX**2/(RX**2 +
     @ RY**2 + (-RZ - SZ)**2)**(3.0d0/2.0d0) + 1/sqrt(RX**2 + RY**2 + (
     @ -RZ - SZ)**2) + (1 - ALPHA)*(-RX**2/(sqrt(RX**2 + RY**2 + (-RZ -
     @ SZ)**2)*(-RZ - SZ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2))**2) +
     @ 1d0/(-RZ - SZ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2)))/ALPHA)

      U1_2 = -6*ALPHA*FP*RX*RY*RZ*SZ/(RX**2 + RY**2 + (-RZ - SZ)**2)**(
     @ 5.0d0/2.0d0) + ALPHA*FP*RX*RY/(RX**2 + RY**2 + (RZ - SZ)**2)**(
     @ 3.0d0/2.0d0) - ALPHA*FP*RX*RY/(RX**2 + RY**2 + (-RZ - SZ)**2)**(
     @ 3.0d0/2.0d0) + 2*FP*(RX*RY/(RX**2 + RY**2 + (-RZ - SZ)**2)**(
     @ 3.0d0/2.0d0) - RX*RY*(1 - ALPHA)/(ALPHA*sqrt(RX**2 + RY**2 + (-RZ
     @ - SZ)**2)*(-RZ - SZ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2))**2))

      U1_3 = -ALPHA*FP*RX*(-RZ - SZ)/(RX**2 + RY**2 + (-RZ - SZ)**2)**(
     @ 3.0d0/2.0d0) + ALPHA*FP*RX*(RZ - SZ)/(RX**2 + RY**2 + (RZ - SZ)**
     @ 2)**(3.0d0/2.0d0) - 2*FP*RZ*(-ALPHA*RX*SZ*(-3*RZ - 3*SZ)/(RX**2 +
     @ RY**2 + (-RZ - SZ)**2)**(5.0d0/2.0d0) - RX*(2 - ALPHA)/(RX**2 +
     @ RY**2 + (-RZ - SZ)**2)**(3.0d0/2.0d0)) + 2*FP*(RX*(-RZ - SZ)/(RX
     @ **2 + RY**2 + (-RZ - SZ)**2)**(3.0d0/2.0d0) - RX*(1 - ALPHA)/(
     @ ALPHA*sqrt(RX**2 + RY**2 + (-RZ - SZ)**2)*(-RZ - SZ + sqrt(RX**2
     @ + RY**2 + (-RZ - SZ)**2))))

      U1_3_px1 = 3*ALPHA*FP*RX**2*(-RZ - SZ)/(RX**2 + RY**2 + (-RZ - SZ)
     @ **2)**(5.0d0/2.0d0) - 3*ALPHA*FP*RX**2*(RZ - SZ)/(RX**2 + RY**2 +
     @ (RZ - SZ)**2)**(5.0d0/2.0d0) - ALPHA*FP*(-RZ - SZ)/(RX**2 + RY**2
     @ + (-RZ - SZ)**2)**(3.0d0/2.0d0) + ALPHA*FP*(RZ - SZ)/(RX**2 + RY
     @ **2 + (RZ - SZ)**2)**(3.0d0/2.0d0) - 2*FP*RZ*(5*ALPHA*RX**2*SZ*(
     @ -3*RZ - 3*SZ)/(RX**2 + RY**2 + (-RZ - SZ)**2)**(7.0d0/2.0d0) -
     @ ALPHA*SZ*(-3*RZ - 3*SZ)/(RX**2 + RY**2 + (-RZ - SZ)**2)**(5.0d0/
     @ 2.0d0) + 3*RX**2*(2 - ALPHA)/(RX**2 + RY**2 + (-RZ - SZ)**2)**(
     @ 5.0d0/2.0d0) - (2 - ALPHA)/(RX**2 + RY**2 + (-RZ - SZ)**2)**(
     @ 3.0d0/2.0d0)) + 2*FP*(-3*RX**2*(-RZ - SZ)/(RX**2 + RY**2 + (-RZ -
     @ SZ)**2)**(5.0d0/2.0d0) + (-RZ - SZ)/(RX**2 + RY**2 + (-RZ - SZ)**
     @ 2)**(3.0d0/2.0d0) + RX**2*(1 - ALPHA)/(ALPHA*(RX**2 + RY**2 + (
     @ -RZ - SZ)**2)*(-RZ - SZ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2))**2
     @ ) + RX**2*(1 - ALPHA)/(ALPHA*(RX**2 + RY**2 + (-RZ - SZ)**2)**(
     @ 3.0d0/2.0d0)*(-RZ - SZ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2))) -
     @ (1 - ALPHA)/(ALPHA*sqrt(RX**2 + RY**2 + (-RZ - SZ)**2)*(-RZ - SZ
     @ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2))))

      U1_3_px2 = 3*ALPHA*FP*RX*RY*(-RZ - SZ)/(RX**2 + RY**2 + (-RZ - SZ)
     @ **2)**(5.0d0/2.0d0) - 3*ALPHA*FP*RX*RY*(RZ - SZ)/(RX**2 + RY**2 +
     @ (RZ - SZ)**2)**(5.0d0/2.0d0) - 2*FP*RZ*(5*ALPHA*RX*RY*SZ*(-3*RZ -
     @ 3*SZ)/(RX**2 + RY**2 + (-RZ - SZ)**2)**(7.0d0/2.0d0) + 3*RX*RY*(2
     @ - ALPHA)/(RX**2 + RY**2 + (-RZ - SZ)**2)**(5.0d0/2.0d0)) + 2*FP*(
     @ -3*RX*RY*(-RZ - SZ)/(RX**2 + RY**2 + (-RZ - SZ)**2)**(5.0d0/2.0d0
     @ ) + RX*RY*(1 - ALPHA)/(ALPHA*(RX**2 + RY**2 + (-RZ - SZ)**2)*(-RZ
     @ - SZ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2))**2) + RX*RY*(1 -
     @ ALPHA)/(ALPHA*(RX**2 + RY**2 + (-RZ - SZ)**2)**(3.0d0/2.0d0)*(-RZ
     @ - SZ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2))))

      U2_1 = -6*ALPHA*FP*RX*RY*RZ*SZ/(RX**2 + RY**2 + (-RZ - SZ)**2)**(
     @ 5.0d0/2.0d0) + ALPHA*FP*RX*RY/(RX**2 + RY**2 + (RZ - SZ)**2)**(
     @ 3.0d0/2.0d0) - ALPHA*FP*RX*RY/(RX**2 + RY**2 + (-RZ - SZ)**2)**(
     @ 3.0d0/2.0d0) + 2*FP*(RX*RY/(RX**2 + RY**2 + (-RZ - SZ)**2)**(
     @ 3.0d0/2.0d0) - RX*RY*(1 - ALPHA)/(ALPHA*sqrt(RX**2 + RY**2 + (-RZ
     @ - SZ)**2)*(-RZ - SZ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2))**2))

      U2_2 = 2*ALPHA*FP*RZ*SZ*(-3*RY**2/(RX**2 + RY**2 + (-RZ - SZ)**2)
     @ **(5.0d0/2.0d0) + (RX**2 + RY**2 + (-RZ - SZ)**2)**(-3.0d0/2.0d0
     @ )) - FP*(ALPHA*RY**2/(RX**2 + RY**2 + (-RZ - SZ)**2)**(3.0d0/
     @ 2.0d0) + (2 - ALPHA)/sqrt(RX**2 + RY**2 + (-RZ - SZ)**2)) + FP*(
     @ ALPHA*RY**2/(RX**2 + RY**2 + (RZ - SZ)**2)**(3.0d0/2.0d0) + (2 -
     @ ALPHA)/sqrt(RX**2 + RY**2 + (RZ - SZ)**2)) + 2*FP*(RY**2/(RX**2 +
     @ RY**2 + (-RZ - SZ)**2)**(3.0d0/2.0d0) + 1/sqrt(RX**2 + RY**2 + (
     @ -RZ - SZ)**2) + (1 - ALPHA)*(-RY**2/(sqrt(RX**2 + RY**2 + (-RZ -
     @ SZ)**2)*(-RZ - SZ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2))**2) +
     @ 1d0/(-RZ - SZ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2)))/ALPHA)

      U2_3 = -ALPHA*FP*RY*(-RZ - SZ)/(RX**2 + RY**2 + (-RZ - SZ)**2)**(
     @ 3.0d0/2.0d0) + ALPHA*FP*RY*(RZ - SZ)/(RX**2 + RY**2 + (RZ - SZ)**
     @ 2)**(3.0d0/2.0d0) - 2*FP*RZ*(-ALPHA*RY*SZ*(-3*RZ - 3*SZ)/(RX**2 +
     @ RY**2 + (-RZ - SZ)**2)**(5.0d0/2.0d0) - RY*(2 - ALPHA)/(RX**2 +
     @ RY**2 + (-RZ - SZ)**2)**(3.0d0/2.0d0)) + 2*FP*(RY*(-RZ - SZ)/(RX
     @ **2 + RY**2 + (-RZ - SZ)**2)**(3.0d0/2.0d0) - RY*(1 - ALPHA)/(
     @ ALPHA*sqrt(RX**2 + RY**2 + (-RZ - SZ)**2)*(-RZ - SZ + sqrt(RX**2
     @ + RY**2 + (-RZ - SZ)**2))))

      U2_3_px1 = 3*ALPHA*FP*RX*RY*(-RZ - SZ)/(RX**2 + RY**2 + (-RZ - SZ)
     @ **2)**(5.0d0/2.0d0) - 3*ALPHA*FP*RX*RY*(RZ - SZ)/(RX**2 + RY**2 +
     @ (RZ - SZ)**2)**(5.0d0/2.0d0) - 2*FP*RZ*(5*ALPHA*RX*RY*SZ*(-3*RZ -
     @ 3*SZ)/(RX**2 + RY**2 + (-RZ - SZ)**2)**(7.0d0/2.0d0) + 3*RX*RY*(2
     @ - ALPHA)/(RX**2 + RY**2 + (-RZ - SZ)**2)**(5.0d0/2.0d0)) + 2*FP*(
     @ -3*RX*RY*(-RZ - SZ)/(RX**2 + RY**2 + (-RZ - SZ)**2)**(5.0d0/2.0d0
     @ ) + RX*RY*(1 - ALPHA)/(ALPHA*(RX**2 + RY**2 + (-RZ - SZ)**2)*(-RZ
     @ - SZ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2))**2) + RX*RY*(1 -
     @ ALPHA)/(ALPHA*(RX**2 + RY**2 + (-RZ - SZ)**2)**(3.0d0/2.0d0)*(-RZ
     @ - SZ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2))))

      U2_3_px2 = 3*ALPHA*FP*RY**2*(-RZ - SZ)/(RX**2 + RY**2 + (-RZ - SZ)
     @ **2)**(5.0d0/2.0d0) - 3*ALPHA*FP*RY**2*(RZ - SZ)/(RX**2 + RY**2 +
     @ (RZ - SZ)**2)**(5.0d0/2.0d0) - ALPHA*FP*(-RZ - SZ)/(RX**2 + RY**2
     @ + (-RZ - SZ)**2)**(3.0d0/2.0d0) + ALPHA*FP*(RZ - SZ)/(RX**2 + RY
     @ **2 + (RZ - SZ)**2)**(3.0d0/2.0d0) - 2*FP*RZ*(5*ALPHA*RY**2*SZ*(
     @ -3*RZ - 3*SZ)/(RX**2 + RY**2 + (-RZ - SZ)**2)**(7.0d0/2.0d0) -
     @ ALPHA*SZ*(-3*RZ - 3*SZ)/(RX**2 + RY**2 + (-RZ - SZ)**2)**(5.0d0/
     @ 2.0d0) + 3*RY**2*(2 - ALPHA)/(RX**2 + RY**2 + (-RZ - SZ)**2)**(
     @ 5.0d0/2.0d0) - (2 - ALPHA)/(RX**2 + RY**2 + (-RZ - SZ)**2)**(
     @ 3.0d0/2.0d0)) + 2*FP*(-3*RY**2*(-RZ - SZ)/(RX**2 + RY**2 + (-RZ -
     @ SZ)**2)**(5.0d0/2.0d0) + (-RZ - SZ)/(RX**2 + RY**2 + (-RZ - SZ)**
     @ 2)**(3.0d0/2.0d0) + RY**2*(1 - ALPHA)/(ALPHA*(RX**2 + RY**2 + (
     @ -RZ - SZ)**2)*(-RZ - SZ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2))**2
     @ ) + RY**2*(1 - ALPHA)/(ALPHA*(RX**2 + RY**2 + (-RZ - SZ)**2)**(
     @ 3.0d0/2.0d0)*(-RZ - SZ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2))) -
     @ (1 - ALPHA)/(ALPHA*sqrt(RX**2 + RY**2 + (-RZ - SZ)**2)*(-RZ - SZ
     @ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2))))

      U3_1 = -ALPHA*FP*RX*(-RZ - SZ)/(RX**2 + RY**2 + (-RZ - SZ)**2)**(
     @ 3.0d0/2.0d0) + ALPHA*FP*RX*(RZ - SZ)/(RX**2 + RY**2 + (RZ - SZ)**
     @ 2)**(3.0d0/2.0d0) + 2*FP*RZ*(-3*ALPHA*RX*SZ*(-RZ - SZ)/(RX**2 +
     @ RY**2 + (-RZ - SZ)**2)**(5.0d0/2.0d0) + RX*(2 - ALPHA)/(RX**2 +
     @ RY**2 + (-RZ - SZ)**2)**(3.0d0/2.0d0)) + 2*FP*(RX*(-RZ - SZ)/(RX
     @ **2 + RY**2 + (-RZ - SZ)**2)**(3.0d0/2.0d0) + RX*(1 - ALPHA)/(
     @ ALPHA*sqrt(RX**2 + RY**2 + (-RZ - SZ)**2)*(-RZ - SZ + sqrt(RX**2
     @ + RY**2 + (-RZ - SZ)**2))))

      U3_2 = -ALPHA*FP*RY*(-RZ - SZ)/(RX**2 + RY**2 + (-RZ - SZ)**2)**(
     @ 3.0d0/2.0d0) + ALPHA*FP*RY*(RZ - SZ)/(RX**2 + RY**2 + (RZ - SZ)**
     @ 2)**(3.0d0/2.0d0) + 2*FP*RZ*(-3*ALPHA*RY*SZ*(-RZ - SZ)/(RX**2 +
     @ RY**2 + (-RZ - SZ)**2)**(5.0d0/2.0d0) + RY*(2 - ALPHA)/(RX**2 +
     @ RY**2 + (-RZ - SZ)**2)**(3.0d0/2.0d0)) + 2*FP*(RY*(-RZ - SZ)/(RX
     @ **2 + RY**2 + (-RZ - SZ)**2)**(3.0d0/2.0d0) + RY*(1 - ALPHA)/(
     @ ALPHA*sqrt(RX**2 + RY**2 + (-RZ - SZ)**2)*(-RZ - SZ + sqrt(RX**2
     @ + RY**2 + (-RZ - SZ)**2))))

      U3_3 = -2*ALPHA*FP*RZ*SZ*(-(-3*RZ - 3*SZ)*(-RZ - SZ)/(RX**2 + RY**
     @ 2 + (-RZ - SZ)**2)**(5.0d0/2.0d0) + (RX**2 + RY**2 + (-RZ - SZ)**
     @ 2)**(-3.0d0/2.0d0)) - FP*(ALPHA*(-RZ - SZ)**2/(RX**2 + RY**2 + (
     @ -RZ - SZ)**2)**(3.0d0/2.0d0) + (2 - ALPHA)/sqrt(RX**2 + RY**2 + (
     @ -RZ - SZ)**2)) + FP*(ALPHA*(RZ - SZ)**2/(RX**2 + RY**2 + (RZ - SZ
     @ )**2)**(3.0d0/2.0d0) + (2 - ALPHA)/sqrt(RX**2 + RY**2 + (RZ - SZ)
     @ **2)) + 2*FP*((-RZ - SZ)**2/(RX**2 + RY**2 + (-RZ - SZ)**2)**(
     @ 3.0d0/2.0d0) + 1/sqrt(RX**2 + RY**2 + (-RZ - SZ)**2) + (1 - ALPHA
     @ )*((-RZ - SZ)/(sqrt(RX**2 + RY**2 + (-RZ - SZ)**2)*(-RZ - SZ +
     @ sqrt(RX**2 + RY**2 + (-RZ - SZ)**2))) + 1d0/(-RZ - SZ + sqrt(RX**
     @ 2 + RY**2 + (-RZ - SZ)**2)))/ALPHA)

      U3_3_px1 = -2*ALPHA*FP*RZ*SZ*(5*RX*(-3*RZ - 3*SZ)*(-RZ - SZ)/(RX**
     @ 2 + RY**2 + (-RZ - SZ)**2)**(7.0d0/2.0d0) - 3*RX/(RX**2 + RY**2 +
     @ (-RZ - SZ)**2)**(5.0d0/2.0d0)) - FP*(-3*ALPHA*RX*(-RZ - SZ)**2/(
     @ RX**2 + RY**2 + (-RZ - SZ)**2)**(5.0d0/2.0d0) - RX*(2 - ALPHA)/(
     @ RX**2 + RY**2 + (-RZ - SZ)**2)**(3.0d0/2.0d0)) + FP*(-3*ALPHA*RX*
     @ (RZ - SZ)**2/(RX**2 + RY**2 + (RZ - SZ)**2)**(5.0d0/2.0d0) - RX*(
     @ 2 - ALPHA)/(RX**2 + RY**2 + (RZ - SZ)**2)**(3.0d0/2.0d0)) + 2*FP*
     @ (-3*RX*(-RZ - SZ)**2/(RX**2 + RY**2 + (-RZ - SZ)**2)**(5.0d0/
     @ 2.0d0) - RX/(RX**2 + RY**2 + (-RZ - SZ)**2)**(3.0d0/2.0d0) + (1 -
     @ ALPHA)*(-RX*(-RZ - SZ)/((RX**2 + RY**2 + (-RZ - SZ)**2)*(-RZ - SZ
     @ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2))**2) - RX*(-RZ - SZ)/((RX**
     @ 2 + RY**2 + (-RZ - SZ)**2)**(3.0d0/2.0d0)*(-RZ - SZ + sqrt(RX**2
     @ + RY**2 + (-RZ - SZ)**2))) - RX/(sqrt(RX**2 + RY**2 + (-RZ - SZ)
     @ **2)*(-RZ - SZ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2))**2))/ALPHA)

      U3_3_px2 = -2*ALPHA*FP*RZ*SZ*(5*RY*(-3*RZ - 3*SZ)*(-RZ - SZ)/(RX**
     @ 2 + RY**2 + (-RZ - SZ)**2)**(7.0d0/2.0d0) - 3*RY/(RX**2 + RY**2 +
     @ (-RZ - SZ)**2)**(5.0d0/2.0d0)) - FP*(-3*ALPHA*RY*(-RZ - SZ)**2/(
     @ RX**2 + RY**2 + (-RZ - SZ)**2)**(5.0d0/2.0d0) - RY*(2 - ALPHA)/(
     @ RX**2 + RY**2 + (-RZ - SZ)**2)**(3.0d0/2.0d0)) + FP*(-3*ALPHA*RY*
     @ (RZ - SZ)**2/(RX**2 + RY**2 + (RZ - SZ)**2)**(5.0d0/2.0d0) - RY*(
     @ 2 - ALPHA)/(RX**2 + RY**2 + (RZ - SZ)**2)**(3.0d0/2.0d0)) + 2*FP*
     @ (-3*RY*(-RZ - SZ)**2/(RX**2 + RY**2 + (-RZ - SZ)**2)**(5.0d0/
     @ 2.0d0) - RY/(RX**2 + RY**2 + (-RZ - SZ)**2)**(3.0d0/2.0d0) + (1 -
     @ ALPHA)*(-RY*(-RZ - SZ)/((RX**2 + RY**2 + (-RZ - SZ)**2)*(-RZ - SZ
     @ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2))**2) - RY*(-RZ - SZ)/((RX**
     @ 2 + RY**2 + (-RZ - SZ)**2)**(3.0d0/2.0d0)*(-RZ - SZ + sqrt(RX**2
     @ + RY**2 + (-RZ - SZ)**2))) - RY/(sqrt(RX**2 + RY**2 + (-RZ - SZ)
     @ **2)*(-RZ - SZ + sqrt(RX**2 + RY**2 + (-RZ - SZ)**2))**2))/ALPHA)

      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      UX = U1_1 * FX + U2_1 * FY + U3_1 * FZ
      UY = U1_2 * FX + U2_2 * FY + U3_2 * FZ
      UZ = U1_3 * FX + U2_3 * FY + U3_3 * FZ
      UZX = U1_3_px1 * FX + U2_3_px1 * FY + U3_3_px1 * FZ
      UZY = U1_3_px2 * FX + U2_3_px2 * FY + U3_3_px2 * FZ
      END
